"""쿠키 분류 데이터"""

COOKIE_ELEMENT = {
    "윈드파라거스 쿠키": "wind",
    "이슬맛 쿠키": "water",
    "멜랑크림 쿠키": "dark",
    "흑보리맛 쿠키": "earth",
    "샤이닝베리맛 쿠키": "light",
    "피닉스페퍼 쿠키": "fire",
    "샬롯맛 쿠키": "dark",
    "네온데니쉬맛 쿠키": "light",
    "룽샤맛 쿠키": "fire",
    "마블베리맛 쿠키": "dark",
    "체리콜라맛 쿠키": "water",
    "블루멜로우맛 쿠키": "water",
    "달빛술사 쿠키": "mystic",
    "밀키웨이맛 쿠키": "mystic",
    "스타더스트 쿠키": "mystic",
    "잭프루트맛 쿠키": "earth",
    "스테인드누가맛 쿠키": "earth",
    "산초맛 쿠키": "earth",
}

COOKIE_TYPE = {
    "윈드파라거스 쿠키": "magic",
    "이슬맛 쿠키": "support",
    "멜랑크림 쿠키": "slash",
    "흑보리맛 쿠키": "shoot",
    "샤이닝베리맛 쿠키": "slash",
    "피닉스페퍼 쿠키": "shoot",
    "샬롯맛 쿠키": "support",
    "네온데니쉬맛 쿠키": "support",
    "룽샤맛 쿠키": "strike",
    "마블베리맛 쿠키": "strike",
    "체리콜라맛 쿠키": "strike",
    "블루멜로우맛 쿠키": "magic",
    "달빛술사 쿠키": "magic",
    "밀키웨이맛 쿠키": "strike",
    "스타더스트 쿠키": "shoot",
    "잭프루트맛 쿠키": "slash",
    "스테인드누가맛 쿠키": "strike",
    "산초맛 쿠키": "support",
}

COOKIE_ROLE = {
    "윈드파라거스 쿠키": "strike",
    "이슬맛 쿠키": "support",
    "멜랑크림 쿠키": "dps",
    "흑보리맛 쿠키": "dps",
    "샤이닝베리맛 쿠키": "dps",
    "피닉스페퍼 쿠키": "dps",
    "샬롯맛 쿠키": "support",
    "네온데니쉬맛 쿠키": "support",
    "룽샤맛 쿠키": "strike",
    "마블베리맛 쿠키": "strike",
    "체리콜라맛 쿠키": "strike",
    "블루멜로우맛 쿠키": "dps",
    "달빛술사 쿠키": "support",
    "밀키웨이맛 쿠키": "strike",
    "스타더스트 쿠키": "dps",
    "잭프루트맛 쿠키": "dps",
    "스테인드누가맛 쿠키": "strike",
    "산초맛 쿠키": "support",
}
